cuda:
  command: nvidia-smi
  devices:
  - /dev/nvidia0
  - /dev/nvidiactl
  - /dev/nvidia-uvm
  image: nvidia/cuda
  volumes:
  - nvidia_driver_367.35:/usr/local/nvidia:ro
tf:
  command: ./notebook.sh
  ports:
    - "8888:8888"
  devices:
  - /dev/nvidia0
  - /dev/nvidiactl
  - /dev/nvidia-uvm
  build: .
  volumes:
  - nvidia_driver_367.35:/usr/local/nvidia:ro
